{
 "title": "ODA",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "projectKey", "label": "Project", "query": "CRYP,AW" },
   {
    "name": "qualifier",
    "label": "CFD Qualifier",
    "query": "All stories and bugs,All stories,All bugs,Critical bugs"
   },
   { "name": "cfdInterval", "label": "CFD Interval", "query": "MONTHS,WEEKS,DAYS" },
   { "name": "jiraInterval", "label": "Interval", "query": "1w,4w" }
  ]
 },
 "panels": [
  {
   "title": "JIRA items by type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "work_items_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "Info" }
     ]
    }
   ]
  },
  {
   "title": "Stories & Bugs added",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$jiraInterval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "work_items_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "Epic" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "Info" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "Sub-task" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "Task" }
     ]
    }
   ]
  },
  {
   "title": "To Do/Done cumulative",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd",
     "query": "SELECT \"To Do\", \"Done\" FROM \"cfd\" WHERE (\"qualifier\" = 'All To Do->Done') AND $timeFilter",
     "select": [
      [
       { "params": [ "To Do" ], "type": "field" }
      ],
      [
       { "params": [ "Done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$qualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=~", "value": "/^$cfdInterval$/" }
     ]
    }
   ]
  },
  {
   "title": "Active team members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$jiraInterval" ], "type": "time" }
     ],
     "measurement": "state_distinct_authors",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "qualifier", "operator": "=", "value": "DEV/QA" }
     ]
    }
   ]
  },
  {
   "title": "CFD",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "measurement": "cfd",
     "select": [
      [
       { "params": [ "CT" ], "type": "field" }
      ],
      [
       { "params": [ "TH" ], "type": "field" }
      ],
      [
       { "params": [ "WIP" ], "type": "field" }
      ],
      [
       { "params": [ "To Do" ], "type": "field" }
      ],
      [
       { "params": [ "Done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "qualifier", "operator": "=~", "value": "/^$qualifier$/" },
      { "condition": "AND", "key": "interval", "operator": "=~", "value": "/^$cfdInterval$/" }
     ]
    }
   ]
  },
  {
   "title": "Team productivity factor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "measurement": "team_productivity_factor",
     "select": [
      [
       { "params": [ "experienceFactor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "TH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd",
     "select": [
      [
       { "params": [ "TH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$qualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=~", "value": "/^$cfdInterval$/" }
     ]
    }
   ]
  },
  {
   "title": "WIP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd",
     "select": [
      [
       { "params": [ "WIP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$qualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=~", "value": "/^$cfdInterval$/" }
     ]
    }
   ]
  },
  {
   "title": "CT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd",
     "select": [
      [
       { "params": [ "CT" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$qualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=~", "value": "/^$cfdInterval$/" }
     ]
    }
   ]
  }
 ]
}