{
 "title": "Gitlab metrics - Merge Requests",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rootNamespace",
    "label": "Root namespace",
    "query": "SHOW TAG VALUES ON \"oda\" WITH KEY = \"rootNamespace\""
   }
  ]
 },
 "panels": [
  {
   "title": "Merge requests by state",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "merge_requests_by_state",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" },
      { "condition": "AND", "key": "root_namespace", "operator": "=~", "value": "/^$rootNamespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Merge requests moving average",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "merge_requests_moving_average",
     "select": [
      [
       { "params": [ "moving_average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" },
      { "condition": "AND", "key": "state", "operator": "=", "value": "merged" },
      { "condition": "AND", "key": "root_namespace", "operator": "=~", "value": "/^$rootNamespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Merge requests by author",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_author",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "author" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "merge_requests_by_author",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Merge requests comments",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_author",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "author" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "merge_requests_comments",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Merge requests duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "merge_requests_duration",
     "select": [
      [
       { "params": [ "duration_avg" ], "type": "field" }
      ],
      [
       { "params": [ "duration_std_dev" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "root_namespace", "operator": "=~", "value": "/^$rootNamespace$/" }
     ]
    }
   ]
  }
 ]
}