{
 "title": "Overview",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "projectKey", "label": "Project", "query": "CRYP,HFT,AW" },
   {
    "name": "cfdQualifier",
    "label": "Qualifier",
    "query": "All stories and bugs,All stories,All bugs,Critical bugs"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd_count",
     "select": [
      [
       { "params": [ "TH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Work items queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "work_items_count_by_state",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "CRYP" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "DAYS" }
     ]
    }
   ]
  },
  {
   "title": "Cycle time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd_count",
     "select": [
      [
       { "params": [ "CT" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Items completed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd_count",
     "select": [
      [
       { "params": [ "Done change" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" },
      { "condition": "AND", "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Merge requests by state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "merge_requests_by_state",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" },
      { "condition": "AND", "key": "root_namespace", "operator": "=", "value": "empirica-algo" }
     ]
    }
   ]
  },
  {
   "title": "Team productivity factor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Experience factor",
     "measurement": "team_productivity_factor",
     "select": [
      [
       { "params": [ "experienceFactor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Active JIRA reporters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "JIRA reporters",
     "measurement": "state_distinct_authors",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "qualifier", "operator": "=", "value": "DEV/QA" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "MONTHS" }
     ]
    }
   ]
  },
  {
   "title": "Active committers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Committers",
     "measurement": "active_committers",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" },
      { "condition": "AND", "key": "rootNamespace", "operator": "=", "value": "empirica-algo" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative flow chart",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd_count",
     "query": "SELECT \"To Do\", \"Done\" FROM \"cfd\" WHERE (\"qualifier\" = 'All To Do->Done') AND $timeFilter",
     "select": [
      [
       { "params": [ "In Progress" ], "type": "field" }
      ],
      [
       { "params": [ "Done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative flow data",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "measurement": "cfd_count",
     "select": [
      [
       { "params": [ "TH" ], "type": "field" }
      ],
      [
       { "params": [ "CT" ], "type": "field" }
      ],
      [
       { "params": [ "In Progress" ], "type": "field" }
      ],
      [
       { "params": [ "Done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  }
 ]
}