{
 "title": "Project roles & categories",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Merge requests by project role",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_role",
     "groupBy": [
      { "params": [ "role" ], "type": "tag" }
     ],
     "measurement": "merge_requests_by_project_role",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Merge requests by project category",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_category",
     "groupBy": [
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "merge_requests_by_project_category",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Commits by project role",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_role",
     "groupBy": [
      { "params": [ "role" ], "type": "tag" }
     ],
     "measurement": "commits_stats_by_project_role",
     "select": [
      [
       { "params": [ "additions" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Commits by project category",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_category",
     "groupBy": [
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "commits_stats_by_project_category",
     "select": [
      [
       { "params": [ "additions" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  }
 ]
}