{
 "title": "Projects metrics",
 "time": { "from": "2019-10-14T23:01:55.920Z", "to": "2020-02-16T08:15:56.114Z" },
 "templating": {
  "list": [
   { "name": "projectKey", "label": "Project", "query": "CRYP,HFT,AW" },
   {
    "name": "cfdQualifier",
    "label": "Qualifier",
    "query": "All stories and bugs,All stories,All bugs,Critical bugs"
   },
   { "name": "cfdMetric", "label": "Metric", "query": "cfd_count,cfd_estimate" }
  ]
 },
 "panels": [
  {
   "title": "Cumulative flow chart",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$cfdMetric$/",
     "query": "SELECT \"To Do\", \"Done\" FROM \"cfd\" WHERE (\"qualifier\" = 'All To Do->Done') AND $timeFilter",
     "select": [
      [
       { "params": [ "In Progress" ], "type": "field" }
      ],
      [
       { "params": [ "Done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$cfdMetric$/",
     "select": [
      [
       { "params": [ "TH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative flow data",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "/^$cfdMetric$/",
     "select": [
      [
       { "params": [ "TH" ], "type": "field" }
      ],
      [
       { "params": [ "CT" ], "type": "field" }
      ],
      [
       { "params": [ "In Progress" ], "type": "field" }
      ],
      [
       { "params": [ "Done" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Cycle time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$cfdMetric$/",
     "select": [
      [
       { "params": [ "CT" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "JIRA items by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "work_items_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "Info" }
     ]
    }
   ]
  },
  {
   "title": "Items completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd_count",
     "select": [
      [
       { "params": [ "Done change" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" },
      { "condition": "AND", "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Active JIRA reporters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "4w" ], "type": "time" }
     ],
     "measurement": "state_distinct_authors",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "qualifier", "operator": "=", "value": "DEV/QA" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "DAYS" }
     ]
    }
   ]
  },
  {
   "title": "Work in progress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cfd_count",
     "select": [
      [
       { "params": [ "WIP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  },
  {
   "title": "Work items duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "work_items_duration",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ],
      [
       { "params": [ "max" ], "type": "field" }
      ],
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "qualifier", "operator": "=~", "value": "/^$cfdQualifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Work items moved to QA/DEV",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "work_items_change_log",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"work_items_change_log\" WHERE (\"project\" =~ /^$projectKey$/ AND (\"type\" = 'Story' OR \"type\" = 'Bug') AND (\"status\" = 'In Progress' OR \"status\" = 'In Review' OR \"status\" = 'Ready to test' OR \"status\" = 'In testing')) AND $timeFilter GROUP BY time(1w), \"status\" fill(previous)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Story" },
      { "condition": "OR", "key": "type", "operator": "=", "value": "Bug" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "In Progress" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "In Review" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "Ready to test" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "In testing" }
     ]
    }
   ]
  },
  {
   "title": "Team productivity factor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "measurement": "team_productivity_factor",
     "select": [
      [
       { "params": [ "experienceFactor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$projectKey$/" },
      { "condition": "AND", "key": "interval", "operator": "=", "value": "WEEKS" }
     ]
    }
   ]
  }
 ]
}